### ISSUE TITLE
Possible dependency conflict

### ISSUE THREAD

**Issue by tvanhens** [k2nr/docker-clj#1]
I am trying to use this library in an experimental project I am working on. When I use the library by itself it works fine. However, when I include it into the project I want to use it in, I get the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at clojure.main.<clinit>(main.java:20)
Caused by: java.io.FileNotFoundException: Could not locate k2nr/docker/container__init.class or k2nr/docker/container.clj on classpath: , compiling:(meiosis/initial_cell.clj:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at meiosis.system$eval757$loading__4958__auto____758.invoke(system.clj:1)
    at meiosis.system$eval757.invoke(system.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:482)
    at user$eval3$loading__4958__auto____4.invoke(user.clj:1)
    at user$eval3.invoke(user.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:357)
    at clojure.lang.RT.maybeLoadResourceScript(RT.java:353)
    at clojure.lang.RT.doInit(RT.java:461)
    at clojure.lang.RT.<clinit>(RT.java:329)
    ... 1 more
Caused by: java.io.FileNotFoundException: Could not locate k2nr/docker/container__init.class or k2nr/docker/container.clj on classpath: 
    at clojure.lang.RT.load(RT.java:443)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:628)
    at clojure.core$use.doInvoke(core.clj:5618)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at meiosis.initial_cell$eval2711$loading__4958__auto____2712.invoke(initial_cell.clj:1)
    at meiosis.initial_cell$eval2711.invoke(initial_cell.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6692)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 50 more
Exception in thread "Thread-5" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
    at clojure.core$ex_info.invoke(core.clj:4327)
    at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
    at clojure.lang.MultiFn.invoke(MultiFn.java:231)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:619)
    at leiningen.repl$server$fn__7443.invoke(repl.clj:201)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1788)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:163)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:621)
    at clojure.core$bound_fn_STAR_$fn__4102.doInvoke(core.clj:1810)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:24)
    at java.lang.Thread.run(Thread.java:695)
```

Also here is the output of my lein deps:

```
WARNING!!! version ranges found for:
[amazonica "0.2.16"] -> [com.amazonaws/aws-java-sdk "1.7.7"] -> [joda-time "[2.2,)"]
Consider using [amazonica "0.2.16" :exclusions [joda-time]].

Possibly confusing dependencies found:
[amazonica "0.2.16"] -> [com.amazonaws/aws-java-sdk "1.7.7"] -> [commons-codec "1.3"]
 overrides
[amazonica "0.2.16"] -> [com.amazonaws/aws-java-sdk "1.7.7"] -> [org.apache.httpcomponents/httpclient "4.2"] -> [commons-codec "1.6"]
 and
[amazonica "0.2.16"] -> [com.amazonaws/amazon-kinesis-client "1.0.0"] -> [org.apache.httpcomponents/httpclient "4.2"] -> [commons-codec "1.6"]
 and
[amazonica "0.2.16"] -> [com.amazonaws/amazon-kinesis-client "1.0.0"] -> [com.amazonaws/aws-java-sdk "1.6.9.1"] -> [org.apache.httpcomponents/httpclient "4.2"] -> [commons-codec "1.6"]

Consider using these exclusions:
[amazonica "0.2.16" :exclusions [commons-codec]]
[amazonica "0.2.16" :exclusions [commons-codec]]
[amazonica "0.2.16" :exclusions [commons-codec]]

 [amazonica "0.2.16"]
   [com.amazonaws/amazon-kinesis-client "1.0.0"]
   [com.amazonaws/aws-java-sdk "1.7.7"]
     [com.fasterxml.jackson.core/jackson-annotations "2.1.1"]
     [com.fasterxml.jackson.core/jackson-core "2.1.1"]
     [com.fasterxml.jackson.core/jackson-databind "2.1.1"]
     [commons-codec "1.3"]
     [commons-logging "1.1.1"]
     [org.apache.httpcomponents/httpclient "4.2"]
       [org.apache.httpcomponents/httpcore "4.2"]
   [com.taoensso/nippy "2.5.0"]
     [org.clojure/tools.reader "0.7.10"]
     [org.iq80.snappy/snappy "0.3"]
     [org.tukaani/xz "1.4"]
   [joda-time "2.2"]
   [org.clojure/algo.generic "0.1.2"]
   [robert/hooke "1.3.0"]
 [clj-base64 "0.0.0-20100308.145053-2"]
   [org.clojure/clojure-contrib "1.1.0"]
 [clj-ssh "0.5.10"]
   [com.jcraft/jsch.agentproxy.core "0.0.7"]
   [com.jcraft/jsch.agentproxy.jsch "0.0.7"]
   [com.jcraft/jsch.agentproxy.pageant "0.0.7"]
   [com.jcraft/jsch.agentproxy.sshagent "0.0.7"]
   [com.jcraft/jsch.agentproxy.usocket-jna "0.0.7"]
     [net.java.dev.jna/jna "3.4.0"]
     [net.java.dev.jna/platform "3.4.0"]
   [com.jcraft/jsch.agentproxy.usocket-nc "0.0.7"]
   [com.jcraft/jsch "0.1.51"]
   [org.clojure/tools.logging "0.2.6" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :exclusions [[org.clojure/clojure]]]
 [com.stuartsierra/component "0.2.1"]
   [com.stuartsierra/dependency "0.1.1"]
 [com.taoensso/timbre "3.2.0"]
   [com.taoensso/encore "1.5.0"]
   [io.aviso/pretty "0.1.10"]
 [org.clojure/clojure "1.6.0"]
 [org.clojure/data.csv "0.1.2"]
 [org.clojure/tools.namespace "0.2.4"]
 [org.clojure/tools.nrepl "0.2.3" :exclusions [[org.clojure/clojure]]]
```

And finally, my project.clj:

```
(defproject meiosis "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure         "1.6.0"]
                 [amazonica                   "0.2.16"]
                 [com.taoensso/timbre         "3.2.0"]
                 [org.clojure/data.csv        "0.1.2"]
                 [com.stuartsierra/component  "0.2.1"]
                 [clj-ssh                     "0.5.10"]
                 [k2nr/docker "0.0.2"]
                 [clj-base64 "0.0.0-SNAPSHOT"]]
  :profiles {:dev {:dependencies [[org.clojure/tools.namespace "0.2.4"]]
                   :source-paths ["dev"]}})

```

I'm just stuck on where to begin. I've tried excluding everything lein deps suggested, but I still get the same error.

**Comment by k2nr** [comment]
I created new project with your `project.clj`, run repl and got the error:

```
user=> (require '[k2nr.docker.container :as c])

CompilerException java.lang.ClassNotFoundException: org.apache.http.conn.ssl.SSLContexts, compiling:(clj_http/conn_mgr.clj:1:1)
```

It seems that library versions are conflicted where `amazonica` uses `[org.apache.httpcomponents/httpclient "4.2"]` but `k2nr.docker` uses `[org.apache.httpcomponents/httpclient "4.3.3"]`. `k2nr.docker` doesn't work with the library version `4.2`.

Maybe the simplest solution is to explicitly use the library version `4.3.3`:

``` clojure
(defproject meiosis "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure         "1.6.0"]
                 [org.apache.httpcomponents/httpclient "4.3.3"] ; <- add this before amazonica
                 [amazonica                   "0.2.16"]
                 [com.taoensso/timbre         "3.2.0"]
                 [org.clojure/data.csv        "0.1.2"]
                 [com.stuartsierra/component  "0.2.1"]
                 [clj-ssh                     "0.5.10"]
                 [k2nr/docker "0.0.2"]
                 [clj-base64 "0.0.0-SNAPSHOT"]]
  :profiles {:dev {:dependencies [[org.clojure/tools.namespace "0.2.4"]]
                   :source-paths ["dev"]}})
```

**Comment by AlwaysBCoding** [comment]
+1  @k2nr ... been struggling with this issue for a while, but just explicitly defining [org.apache.httpcomponents/httpclient "4.3.3"] in the project.clj did the trick.

**Comment by arichiardi** [comment]
I would like to start using this tool exactly with AWS, can I help for solving this problem in some way? Probably the `:exclusions` clause is necessary when importing `docker-clj`?

I had to include `[clj-http "2.2.0"]` in order for this to work properly, I was receiving  a `clj-http.header` missing error as well.
